version: '3.8'
name: patrol-tech

services:
  mariadb:
    image: mariadb:10.3
    container_name: patrol_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'patrol'
      MYSQL_USER: 'patrol'
      MYSQL_PASSWORD: 'patrol'
      MYSQL_ROOT_PASSWORD: 'patrol'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
